# Generated by Django 5.2.3 on 2025-06-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_remove_course_duration_course_code'),
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='teachers', to='course_app.course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='teacher@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default='Teacher', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='User', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='timing',
            field=models.CharField(default='Morning', max_length=100),
        ),
    ]
