# Generated by Django 5.2.3 on 2025-06-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0003_studentmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='marks_for',
            field=models.CharField(choices=[('Midterm', 'Midterm'), ('Final', 'Final'), ('Quiz', 'Quiz'), ('Assignment', 'Assignment'), ('Other', 'Other')], default='Midterm', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='exam_date',
            field=models.DateField(),
        ),
    ]
