# Generated by Django 5.2.3 on 2025-06-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='DEFAULT-CODE', max_length=20, unique=True),
        ),
    ]
