# Generated by Django 5.2.3 on 2025-06-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_remove_course_duration_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='timing',
            field=models.CharField(default='morning', max_length=100),
        ),
    ]
